name: SimpleHomes
version: maven-version-number
description: Plugin that allows players to use homes.
authors: [Lanky_Lord, cedeel]
website: https://github.com/LankyLord/SimpleHomes

main: net.lankylord.simplehomes.SimpleHomes
database: false

commands:
  sethome:
    description: Set your home.
    permission: simplehomes.homes
  home:
    description: Teleport back to your set home.
    permission: simplehomes.homes
  otherhome:
    description: Teleport to another player's sethome.
    permission: simplehomes.otherhomes
    usage: "Usage: /otherhome <PlayerName> (HomeName)?"
  homelist:
    description: Get a list of homes
    permission: simplehomes.multihomes
  delhome:
    description: Delete a home
    permission: simplehomes.homes
    
permissions:
  simplehomes.*:
    description: All SimpleHomes permissions
    children:
      simplehomes.homes: true
      simplehomes.multihomes: true
      simplehomes.otherhomes: true
  simplehomes.homes:
    description: Allows you to set a home and teleport to it.
    default: true
  simplehomes.multihomes:
    description: Allows you to set multiple homes.
    children:
      simplehomes.homes: true
    default: true
  simplehomes.otherhomes:
    description: Allows you to teleport to other people's homes.
    default: op
