name: SimpleHomes
version: 1.5
description: Plugin that allows players to use homes.
author: Lanky_Lord
website: https://github.com/LankyLord/SimpleHomes

main: com.github.lankylord.SimpleHomes.SimpleHomes
database: false

commands:
  sethome:
    description: Set your home.
    permission: simplehomes.homes
  home:
    description: Teleport back to your set home.
    permission: simplehomes.homes
  otherhome:
    description: Teleport to another player's sethome.
    permission: simplehomes.otherhomes
  homelist:
    description: Get a list of homes
    permission: simplehomes.multihomes
    
permissions:
  simplehomes.*:
    description: All SimpleHomes permissions
    children:
      simplehomes.homes: true
      simplehomes.multihomes: true
      simplehomes.otherhomes: true
  simplehomes.homes:
    description: Allows you to set a home and teleport to it.
    default: true
  simplehomes.multihomes:
    description: Allows you to set multiple homes.
    default: true
  simplehomes.otherhomes:
    description: Allows you to teleport to other people's homes.
    default: op