name: SimpleHomes
main: com.github.lankylord.simplehomes
version: 1.1
description: >
             A simple no-nonsense plugin, that allows people to set a home and teleport back to it.
commands:
  sethome:
    description: Set your home.
  home:
    description: Teleport back to your set home.