name: SimpleHomes
version: 1.2
description: A simple plugin to implement homes on a server.
author: Lanky_Lord
website: https://github.com/LankyLord/SimpleHomes

main: com.github.lankylord.SimpleHomes
database: false

description: A simple plugin to implement homes on a server.
commands:
  sethome:
    description: Set your home.
    permission: simplehomes.homes
  home:
    description: Teleport back to your set home.
    permission: simplehomes.homes
    
permissions:
  simplehomes.*:
    description: All SimpleHomes permissions
    children:
      simplehomes.homes: true
      simplehomes.otherhomes: true
  simplehomes.homes:
    description: Allows you to set a home and teleport to it.
    default: true
  simplehomes.otherhomes:
    description: Allows you to teleport to other people's homes.
    default: op